[toolchain]

[features]
seeds = false
skip-lint = false

[workspace]
members = [
    "src/programs/job-platform"
]

[programs.localnet]
job-platform = "2bZY4L2gTev6uBoxBoxUefRMJFM61xay53PvPgkxeeuY"

[programs.devnet]
job-platform = "2bZY4L2gTev6uBoxBoxUefRMJFM61xay53PvPgkxeeuY"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "wallets/deployer-wallet.json"

[scripts]
test = "npm run ts-mocha -p ./config/tsconfig.json -t 1000000 tests/**/*.ts"